### ISSUE TITLE
The complete code package about the pytorch version

### ISSUE THREAD

**Issue by PatrickWilliams44** [j-sripad/mulitresunet-pytorch#2]
Hi! I have read the paper "MultiResUNet : Rethinking the U-Net Architecture for Multimodal Biomedical Image Segmentation" recently, and now I want to reproduce the code corresponding to the paper. I am honored to see your research on the pytorch version. Could you please provide pytorch version of the complete code package? 
The gratitude is beyond words! Looking forward to your early reply!

**Comment by j-sripad** [comment]
Hi. Thank you.
What exactly do you mean by complete code package?

Thanks,
Sripad

**Comment by PatrickWilliams44** [comment]
Hi!  Thank you very much for your reply. 
The complete code package means that it contains code such as model, train, test, etc.
I would be grateful if you could share it.
Thanks again!

**Comment by j-sripad** [comment]
Hi, I am sorry I currently don't have the complete code package I used to train this model. Please refer - https://github.com/j-sripad/colon_crypt_segmentation/blob/master/Training.ipynb , It contains a well defined train loop, you will just need to use this multiresnet model there. Hope you find it useful.

Thanks
Sripad
